# this goes inside _config.yml. Change as required
navigation:
        - text: RightingCode.org
          url: /index.html
        - text: People
          url: /people.html
        - text: Prereqs
          url: /ready.html
        - text: Lessons
          url: /lessons.html
        - text: Labs
          url: /labs.html
toolname: RightingCode
