# this goes inside _config.yml. Change as required
navigation:
        - text: Home
          url: /index.html
        - text: People
          url: /people.html
        - text: Prereqs
          url: /ready.html
        - text: Lectures
          url: /lectures.html
        - text: Labs
          url: /labs.html
        - text: Resources
          url: /resources.html
toolname: RightingCode
